"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$character"""

add_newline = true

[character]
success_symbol = "[](bold #7aa2f7)"
error_symbol = "[](bold #f7768e)"
vimcmd_symbol = "[](bold #9ece6a)"

[directory]
style = "bold #e4e4e4"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"dev" = ""

[git_branch]
symbol = ""
style = "#6b6b6b"
format = 'on [$symbol $branch]($style) '

[git_status]
style = "#f7768e"
format = '[$all_status$ahead_behind]($style)'
